apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  nodeSelector:
    group: {{ .Values.nodeSelector.group }}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - {{ .Values.podTypeLabel }}
          topologyKey: "kubernetes.io/hostname"
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - {{ .Values.availabilityZone }}


